name: ci

#on:
#  push:
#    branches:
#      - master

on:
  workflow_run:
    workflows: ["update base docker image"]
    branches:
      - master
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    container: tandav/musictool-stream-base
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: lint
        run: make check-lint

      - name: test
        run: make test

  publish-docker-image:
    name: build and publish musictool-stream docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      #      - name: save commit messages
      #        run: make messages
      #
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v1
      #
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1
      #
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ls
        run: |
          pwd
          ls -hAlt
          ls -hAlt static

      - name: dockerhub login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: make build_push

  test-container:
    needs: publish-docker-image
    name: test render inside brand new docker coontainer
    runs-on: ubuntu-latest
    container: tandav/musictool-stream
    steps:
      - name: test render
        run: |
          cd /app
          python -m musictool_stream.daw video_test

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v2
#        with:
#          platforms: linux/amd64,linux/arm64/v8
#          push: true
#          tags: tandav/musictool-stream
